GRID_ROWS = 25
GRID_COLUMNS = 50

BACKGROUND_COLOR = (0, 128, 0)
X_RAY_BACKGROUND = (6, 13, 4)
X_RAY_LINES = (21, 63, 31)
WINDOW_HEIGHT = 500
WINDOW_WIDTH = 1000

SOLDIER_STARTING_PLACE=[0,0]

SOLDIER_IMG = "soldier.png"
SOLDIER_NIGTH_IMG = "soldier_nigth.png"
EXPLOTION_IMG = "explotion.png"
MINE_IMG = "mine.png"
GRASS_IMG = "grass.png"
FLAG_IMG = "flag.png"
WINNER_IMG ="winner.png"


MINE="mine"
EMPTY="empty"
FLAG="flag"

FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = (0,0,0)
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (0,0,0)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))
